import smtplib
import os
from dotenv import load_dotenv
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
# Import the recommendation generation function from the external AI advisor module
from ai_advisor import get_movie_recommendation

# Load configuration settings and secrets (email credentials) from the .env file
load_dotenv()

# Dictionary containing the current user profile parameters for content targeting
user_profile = {
    "age_group": "adult", 
    "interest": "action"
}

# Initialize local variables with values fetched from the system environment
my_email = os.getenv("EMAIL_USER")  # Sender's email address
my_password = os.getenv("EMAIL_PASS")  # App-specific authorization token (App Password)
target_email = "daniltaran1234@gmail.com"  # Recipient's email address

print("Starting text generation...")
# Sequential AI calls to generate personalized content for each movie individually
desc_1 = get_movie_recommendation("Інтерстеллар", user_profile["age_group"], user_profile["interest"])
desc_2 = get_movie_recommendation("Той що біжить лабіринтом", user_profile["age_group"], user_profile["interest"])
desc_3 = get_movie_recommendation("Пірати Карибського моря", user_profile["age_group"], user_profile["interest"])

# Create a composite MIME object (container) to assemble the electronic mail structure
message = MIMEMultipart()
message["From"] = f"MOVIE ADVISOR <{my_email}>"  # Metadata: sender header field
message["To"] = target_email  # Metadata: recipient header field
message["Subject"] = "Your AI Personalized Selection"  # Metadata: email subject line

# Define the HTML markup structure and inline CSS styles for visual email formatting
html = f"""
<html>
<body style="font-family: Arial, sans-serif; background-color: #2c2c2e; color: #ffffff; margin: 0; padding: 40px 0;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #1a1a1b; padding: 40px; border-radius: 8px;">
        
        <div style="text-align: center; margin-bottom: 50px;">
            <h1 style="color: #e50914; margin: 0; font-size: 32px; letter-spacing: 2px; font-weight: bold;">MOVIE ADVISOR</h1>
        </div>

        <div style="margin-bottom: 40px;">
            <p style="font-size: 18px; font-weight: bold; margin-bottom: 10px;">Ми підібрали фільми спеціально для вас.</p>
            <p style="font-size: 14px; color: #a1a1a4; line-height: 1.5;">Грунтуючись на ваших минулих переглядах, ці хіти можуть вам сподобатися:</p>
        </div>

        <div style="padding: 20px 0; border-bottom: 1px solid #333;">
            <strong style="font-size: 20px; display: block; margin-bottom: 8px;">Інтерстеллар</strong>
            <p style="color: #e50914; font-size: 14px; margin: 0;">{desc_1}</p>
        </div>

        <div style="padding: 20px 0; border-bottom: 1px solid #333;">
            <strong style="font-size: 20px; display: block; margin-bottom: 8px;">Той що біжить лабіринтом</strong>
            <p style="color: #e50914; font-size: 14px; margin: 0;">{desc_2}</p>
        </div>

        <div style="padding: 20px 0; border-bottom: 1px solid #333; margin-bottom: 40px;">
            <strong style="font-size: 20px; display: block; margin-bottom: 8px;">Пірати Карибського моря</strong>
            <p style="color: #e50914; font-size: 14px; margin: 0;">{desc_3}</p>
        </div>

        <div style="text-align: center; margin-top: 50px;">
            <p style="font-size: 12px; color: #636366; font-style: italic;">Приємного перегляду!</p>
        </div>

    </div>
</body>
</html>
"""
# Encapsulate the HTML string into a text-type MIME object and attach it to the root message container
message.attach(MIMEText(html, "html"))

# Exception handling block to maintain network session stability
try:
    # Establish a TCP connection with Google's SMTP server on standard TLS port 587
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()  # Upgrade the connection to a secure TLS encrypted mode
        server.login(my_email, my_password)  # Authenticate with the server using the provided credentials
        
        # Validate and transmit the assembled data packet cast into a string format
        server.sendmail(my_email, target_email, message.as_string())
    
    print("Email successfully generated by AI and dispatched!")

except Exception as error:
    # Log errors in case of an unsuccessful SMTP session or authentication breakdown
    print(f"Delivery failed: {error}")